spring:
  application:
    name: tekken-analytics

  datasource:
    url: jdbc:postgresql://localhost:5432/tekken
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 16
      minimum-idle: 8
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

  rabbitmq:
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 50
        default-requeue-rejected: false

springdoc:
  swagger-ui:
    path: /swagger-ui

  api-docs:
    path: /api-docs